  operation:
    required: false
    displayName: operation
    description: |
      **operation** can be *insert_after*, *insert_before*, *insert_top*, or
      *insert_before_default*.
  anchorId:
    required: false
    displayName: anchorId
    description: |
      Specify the section ID to use for reference with *insert_before* or
      *insert_after* operations.
